### ISSUE TITLE
Unable to Set Up Repo - stoppur

### ISSUE THREAD

**Issue by stoppur** [uwhpsc-2016/homework1#10]
I followed the invitation and have logged out and tried again multiple times. My error messages alternate between: "Cannot retrieve this organizations repo plan, please reauthenticate your token." and "You are forbidden from performing this action on github.com". I've tried directly accessing https://github.com/uwhpsc-2016/homework1-stoppur but it tells me the page doesn't exist

**Comment by quantheory** [comment]
That's odd; I clicked on that link and there is a private repo there. Can you try again?

**Comment by stoppur** [comment]
That's really strange, I'm following the same link and I still get a 404

**Comment by quantheory** [comment]
It looks like the repos have been created, but somehow they are private repos that you don't have permission to view. Maybe @cswiercz can ask GitHub about it (or maybe we can delete the repo there and have you try again). @Marisa67 has the same issue I think.

**Comment by cswiercz** [comment]
@stoppur Try navigating here now: https://github.com/uwhpsc-2016/homework1-stoppur Let me know if this works.

@quantheory @mvelegar The problem with some (and only some) of the repos is that GitHub isn't properly adding the student to the "Collaborators" list. My solution so far has been to manually add the student, myself. (Settings -> Collaborators & teams -> Collaborators)

**Comment by stoppur** [comment]
This is working for me now, thank you!
