### ISSUE TITLE
Unable to Set Up Repo - yusufmansour

### ISSUE THREAD

**Issue by yusufmansour** [uwhpsc-2016/homework1#15]
I've gotten a few different error messages, but the latest is "Repository: name already exists on this account." I don't see this repo under my user profile. I also tried getting there from https://github.com/uwhpsc-2016/homework1-yusufmansour and I got error 404.

**Comment by quantheory** [comment]
Try again now.

**Comment by yusufmansour** [comment]
it works, thank you!
