### ISSUE TITLE
Cannot Accept Homework Invitation

### ISSUE THREAD

**Issue by astrophpeter** [uwhpsc-2016/homework1#2]
# Description

Cannot accept the invitation to homework one from the link in the email
# Attempted Fixes

Signing out and back into git hub
# Error Message(s)

I get one of the following errors when I try and accept:

Cannot retrieve this organizations repo plan, please reauthenticate your token.
Repository: name already exists on this account.
You are forbidden from performing this action on github.com

**Comment by cswiercz** [comment]
Your repository has been created: https://github.com/uwhpsc-2016/homework1-petermcgill94

I think there was a timing issue where the repo was created but the fact that it was created was not reported in time. I'm not sure why this occurred. I've contacted GitHub about this.

**Comment by akihis2** [comment]
I am not sure if I should start a new issue or should just post here, but I am having exact same issue when I am trying to accept the invite. I have signed out from GitHub completely, waited 10 or mote minute, cleared all data from browser, and tried again, but it does not seem to help. GitHub also gives 404 error page if I try to navigate to the URL of the repository manually using the instruction given in the most recent email.

**Comment by astrophpeter** [comment]
I am having the same problem as @akihis2, still.

**Comment by cswiercz** [comment]
@akihis2 @petermcgill94 I just now tried to manually give each of you read/write access to your respective repositories.
- akihis2 - https://github.com/uwhpsc-2016/homework1-akihis2
- petermcgill94 - https://github.com/uwhpsc-2016/homework1-petermcgill94

Let me know if this works.

**Comment by astrophpeter** [comment]
Issue resolved, thanks!

**Comment by qpskcn1** [comment]
I am having the same issue as well.
I have already tried to restart the browser completely and wait like 10 minutes, still not worked.

**Comment by cswiercz** [comment]
@qpskcn1 From my end it looks like your situation is a bit different from the others since a private repo hasn't even been created. I have emailed GitHub about this issue and will let you know the status.

**Comment by akihis2** [comment]
Issue resolved as well. Thank you for your quick help.

**Comment by briankchan** [comment]
I also still have this issue after logging out and back in and trying a different browser.

**Comment by cswiercz** [comment]
@qpskcn1 I just received a notification that your private repo was created. Let me know if you able to access it at  https://github.com/uwhpsc-2016/homework1-qpskcn1

@iluvredwall I'm not sure if @qpskcn1 's repo just took a long time to create (for whatever reason on GitHub's end) or if I needed to prod GitHub for them to finish the job. I will let you know when I receive a notification that your repo has been created.

**Comment by qpskcn1** [comment]
@cswiercz I just randomly reopened the link and accepted the homework successfully. 
Thank you so much!

**Comment by cswiercz** [comment]
> @cswiercz I just accepted the homework and successfully, thank you so much!

Whew! That’s a relief.

**Comment by joekasp** [comment]
I've tried everything described (logging out, different browsers, waiting) and still no luck.

**Comment by werrah** [comment]
I'm having the same issue.

**Comment by atom-moyer** [comment]
I have the same problem too.

**Comment by cswiercz** [comment]
@iluvredwall @joekasp @werrah @atom-moyer Unfortunately, this seems to be an issue on GitHub's end. Follow the instructions I emailed the class about here: https://canvas.uw.edu/courses/1038251/discussion_topics/3298851

If you've followed these instructions already can you confirm that they worked / didn't work?

**Comment by joekasp** [comment]
@cswiercz I just got a reply from the GitHub Education staff:

> Hi joekasp,
> 
> If you are still experiencing this issue please have your instructor log out of Classroom for GitHub, then log back in. If the issue persists then your instructor should open an issue here:
> 
> https://github.com/education/classroom/issues
> 
> Cheers,
> Scott

**Comment by cswiercz** [comment]
Are you able to access https://github.com/uwhpsc-2016/homework1-joekasp ?

**Comment by werrah** [comment]
I got the same response.

I am unable to access. https://github.com/uwhpsc-2016/homework1-werrah

**Comment by cswiercz** [comment]
> I am unable to access. https://github.com/uwhpsc-2016/homework1-werrah

Try now. The repo exists but GitHub has their permissions mixed up.

**Comment by werrah** [comment]
That works. Thank you so much!

**Comment by cswiercz** [comment]
> That works. Thank you so much!

Great!

**Comment by cswiercz** [comment]
To anyone posting in this thread, please create separate Homework 1 Issue so I can better keep track of who still needs assistance.
