### ISSUE TITLE
Exercise 3.7 Is A diagonally dominant?

### ISSUE THREAD

**Issue by acordonez** [uwhpsc-2016/homework1#41]
Is matrix A in problem 3.7 strictly diagonally dominant (32x32 array of 1's with -5 on the main diagonal)? It doesn't seem like it is to me, but maybe I'm misunderstanding the definitions I've found online or the conditions under which the functions in exercise 3 should work.

**Comment by mvelegar** [comment]
The matrix A has 5 diagonals only: -5's along the main diagonal and 1's along the -2, -1, +1, and +2 subdiagonals. So for any row i |a_ii|=5>sum of the absolute value of 4 off diagonal elements=4. A is SDD.

**Comment by acordonez** [comment]
Ok, I see that. Thank you!
