### ISSUE TITLE
Unable to setup repo - joekasp

### ISSUE THREAD

**Issue by joekasp** [uwhpsc-2016/homework1#5]
I've tried accessing the link [https://github.com/uwhpsc-2016/homework1-joekasp](https://github.com/uwhpsc-2016/homework1-joekasp) but to no avail. Still getting errors if I try accepting the assignment. Restarting my computer (as well as logging in/out) didn't do anything either.

**Comment by cswiercz** [comment]
Try now. Let me know if it works.

**Comment by joekasp** [comment]
Yes, thank you!
