### ISSUE TITLE
SageMath cannot load my report.PDF file

### ISSUE THREAD

**Issue by sarahmagluyan** [uwhpsc-2016/homework1#50]
I navigated in SageMath cloud to view the report.pdf document that I had made to make sure that it looked okay, but I keep getting a message saying that it "Failed to load the PDF document". Should I be concerned that there is something wrong with the file I created which is resulting in SageMath not being about to read it and why it isn't showing up? 

I created the doc by using emacs report.pdf, I entered in all my answers and committed it to my local repo successfully before checking through the SageMath navigator.

Thanks!

**Comment by cswiercz** [comment]
> I created the doc by using emacs report.pdf, I entered in all my answers and committed it to my local repo successfully before checking through the SageMath navigator.

You cannot create PDF files using emacs. PDFs are in a proprietary binary format. Just because it's called "`report.pdf`" doesn't make it a PDF-formatted file.

**Comment by sarahmagluyan** [comment]
That would certainly explain things haha. I will defer to the method explained in lectures then. Thank you!
