### ISSUE TITLE
Latex in Jupyter

### ISSUE THREAD

**Issue by ckchmod** [uwhpsc-2016/homework1#54]
I'm working on putting a finishing touch on the report. As shown in class, I'm trying to use Jupyter, and export the Jupyter file as Latex PDF. But it seems like you can't edit the LaTeX itself in the markdown cells in Jupyter, is that correct?

For example, I would like to edit the space between the title and date, take out numbering in sections,add line breaks between paragraphs in markdown, etc... , but I'm not sure where you'd make those changes in Jupyter. 

![latex editing](https://cloud.githubusercontent.com/assets/5385567/14748610/77068750-086f-11e6-9e95-58e2ad1ac28b.PNG)

**Comment by mvelegar** [comment]
@cswiercz could you comment on if and how this could be done?

**Comment by cswiercz** [comment]
I don't know how to edit the TeX file directly. One sufficient solution would be to rename your worksheet like so:

![foo](https://cloud.githubusercontent.com/assets/915840/14796343/b2e27cf6-0ae1-11e6-923e-584f10dc10c3.png)

Which results in the following document:

![bar](https://cloud.githubusercontent.com/assets/915840/14796372/cc4c20ca-0ae1-11e6-9485-6d0df04255a9.png)

**Comment by ckchmod** [comment]
I see. I'm not sure if I'll have time before submission to change the format, but thank you!
