### ISSUE TITLE
Unable to Set Up Repo - atom-moyer

### ISSUE THREAD

**Issue by atom-moyer** [uwhpsc-2016/homework1#6]
I have messaged github and received a response.  I still do not have permission.

**Comment by cswiercz** [comment]
Try now. Let me know if it works.

**Comment by cswiercz** [comment]
Specifically, try accessing https://github.com/uwhpsc-2016/homework1-atom-moyer

**Comment by atom-moyer** [comment]
Yes, I am able to access. Thanks.
