### ISSUE TITLE
Unable to Set Up Repo - kayarre

### ISSUE THREAD

**Issue by kayarre** [uwhpsc-2016/homework1#9]
gettings errors like 
Cannot retrieve this organizations repo plan, please reauthenticate your token.

or You are forbidden from performing this action on github.com

i tried logging in and out to no avail.

**Comment by cswiercz** [comment]
Try navigating to https://github.com/uwhpsc-2016/homework1-kayarre now. Let me know if this works.

**Comment by kayarre** [comment]
works now.
